/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import model.item_Tour;

import Constant.CommonConstant;
import model.User;
import model.current_User;

import javax.swing.*;
import java.sql.*;

import static java.sql.DriverManager.*;
/**
 *
 * @author Admin
 */
public class Item_Tour extends javax.swing.JPanel {

    /**
     * Creates new form Item_Tour
     */
    public Item_Tour() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shape_roundboder1 = new View.shape_roundboder();
        round_img1 = new View.round_img();
        txttnameTour = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        addButton = new javax.swing.JLabel();

        round_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paris_full.jpg"))); // NOI18N
        round_img1.setOpaque(false);

        javax.swing.GroupLayout round_img1Layout = new javax.swing.GroupLayout(round_img1);
        round_img1.setLayout(round_img1Layout);
        round_img1Layout.setHorizontalGroup(
            round_img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        round_img1Layout.setVerticalGroup(
            round_img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        txttnameTour.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        txttnameTour.setText("TOUR NGẮM THÁP EFFIEL");

        txtPrice.setFont(new java.awt.Font("Open Sans Condensed ExtraBold", 0, 18)); // NOI18N
        txtPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyicon.png"))); // NOI18N
        txtPrice.setText("150");

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueaddicon.png"))); // NOI18N
        addButton.setText("jLabel6");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout shape_roundboder1Layout = new javax.swing.GroupLayout(shape_roundboder1);
        shape_roundboder1.setLayout(shape_roundboder1Layout);
        shape_roundboder1Layout.setHorizontalGroup(
            shape_roundboder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shape_roundboder1Layout.createSequentialGroup()
                .addGroup(shape_roundboder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(round_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, shape_roundboder1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(shape_roundboder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttnameTour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        shape_roundboder1Layout.setVerticalGroup(
            shape_roundboder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shape_roundboder1Layout.createSequentialGroup()
                .addComponent(round_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttnameTour, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(shape_roundboder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shape_roundboder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shape_roundboder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private String title;
    private String price;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPrice() {
        return price;

    }

    public void setPrice(String price) {
        this.price = price;
    }

    private void addItemToDB(String nametour, String price){
        try{
            Connection connection = getConnection(CommonConstant.DB_URL, CommonConstant.DB_USERNAME, CommonConstant.DB_PASSWORD);
            PreparedStatement insertTour = connection.prepareStatement(
                    "INSERT INTO " + CommonConstant.TABLE_TOUR + " (Tour_name, Price)" + " VALUES (?, ?)"
            );
            insertTour.setString(1, nametour);
            insertTour.setString(2, price);
            insertTour.executeUpdate();
            System.out.println("them thanh cong");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public int i=1;
    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:
        String nameTour = txttnameTour.getText();
        String price = txtPrice.getText();
        item = new item_Tour(nameTour, price);
        addItemToDB(nameTour, price);
    }//GEN-LAST:event_addButtonMouseClicked

    public JLabel getTxtPrice() {
        return txtPrice;
    }

    public void setTxtPrice(String txtPrice) {
        this.txtPrice.setText(txtPrice);
    }

    public JLabel getTxttnameTour() {
        return txttnameTour;
    }

    public void setTxttnameTour(String txttnameTour) {
        this.txttnameTour.setText(txttnameTour);
    }

    public void setRound_img1(Icon img) {
        round_img1.setIcon(img);
    }
    private item_Tour item;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addButton;
    private View.round_img round_img1;
    private View.shape_roundboder shape_roundboder1;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txttnameTour;
    // End of variables declaration//GEN-END:variables
}
