/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Database.Connect_to_DB;
import model.User;
import model.current_User;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;
import javax.swing.border.LineBorder;

/**
 *
 * @author Admin
 */
public class UI_Login extends FormUI {

    /**
     * Creates new form Form_login
     */
    public UI_Login() {
//        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        sign_in_button1 = new View.Sign_in_button();
        txt_error = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 249, 249));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(355, 428));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 65, 187));
        jLabel1.setText("Login here");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(105, 67, 138, 33);

        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username);
        txt_username.setBounds(40, 184, 280, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 37, 37));
        jLabel2.setText("Welcome back you've  been missed!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(73, 112, 206, 16);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 162, 59, 16);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 226, 56, 15);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(73, 73, 73));
        jLabel6.setText("Create new account");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 370, 114, 14);

        jLabel7.setForeground(new java.awt.Color(54, 84, 194));
        jLabel7.setText("Forgot your password?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 300, 150, 15);

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(40, 253, 280, 35);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gg2.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton2);
        jButton2.setBounds(50, 430, 61, 53);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fb2.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 430, 61, 53);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/github1.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton4);
        jButton4.setBounds(230, 430, 61, 53);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture3.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 540, 355, 160);

        sign_in_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_in_button1MouseClicked(evt);
            }
        });
        jPanel1.add(sign_in_button1);
        sign_in_button1.setBounds(40, 320, 280, 40);
        jPanel1.add(txt_error);
        txt_error.setBounds(50, 390, 210, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(760, 0, 350, 680);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhminhhoalon_rs.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 770, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        UI_Login.this.dispose();
        new UI_Register().setVisible(true);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void bgimg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgimg1MouseClicked
            
    }//GEN-LAST:event_bgimg1MouseClicked
   
    private void switchMainUI(){
        UI_Login.this.dispose();
        new UI_MAIN().setVisible(true);
    }
    
    private void sign_in_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_in_button1MouseClicked
        // TODO add your handling code here:
        String username = txt_username.getText();
        String password = new String(jPasswordField1.getPassword());

        if (Connect_to_DB.validateLogin(username, password)) {
//            JOptionPane.showMessageDialog(this, "Login Successful!");
            txt_error.setText("");
            switchMainUI();
        } else {
//            JOptionPane.showMessageDialog(this,"Username or password incorrect!" );
            txt_username.setBorder(new LineBorder(Color.RED, 1));
            jPasswordField1.setBorder(new LineBorder(Color.RED, 1));
            txt_error.setText("Username or password incorrectly!");
            shake(jPasswordField1);
            shake(txt_username);
            txt_error.setForeground(Color.RED);
            txt_username.setText("");
            txt_username.requestFocus(); // Đảm bảo focus nằm trong trường văn bản
            txt_username.repaint(); // Làm mới giao diện của thành phần
            jPasswordField1.setText("");

        }

    }//GEN-LAST:event_sign_in_button1MouseClicked
    private static final int SHAKE_DURATION = 500; // Thời gian rung (ms)
    private static final int SHAKE_DISTANCE = 2; // Khoảng cách rung (pixel)
    private void shake(JComponent component) {
        int posx = component.getX();
        Timer timer = new Timer(50, null);
        timer.addActionListener(new ActionListener() {
            int shakes = 0;
            int direction = 1; // 1 = phải, -1 = trái

            @Override
            public void actionPerformed(ActionEvent e) {

                if (shakes < SHAKE_DURATION / 50) { // Chạy trong thời gian chỉ định
                    int x = component.getX() + (direction * SHAKE_DISTANCE);
                    component.setLocation(x, component.getY());
                    direction *= -1; // Đổi hướng
                    shakes++;
                } else {
                    timer.stop(); // Dừng timer
                    component.setLocation(posx, component.getY()); // Trở về vị trí ban đầu (có thể thay đổi vị trí này)
                    txt_username.setBorder(new LineBorder(Color.BLACK, 1));
                    jPasswordField1.setBorder(new LineBorder(Color.BLACK, 1));
                }
            }
        });

        timer.start(); // Bắt đầu rung
    }

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked
        //TODO add your handling code here:

    }//GEN-LAST:event_txt_usernameMouseClicked


    public JTextField get_username() {
        return txt_username;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private View.Sign_in_button sign_in_button1;
    private javax.swing.JLabel txt_error;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
