/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Constant.CommonConstant;
import Database.Connect_to_DB;
import model.current_User;
import module.Controller_Table_User;
import module.addUser;


import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static java.sql.DriverManager.getConnection;

/**
 *
 * @author Admin
 */
public class UI_MAIN extends javax.swing.JFrame {

    /**
     * Creates new form UI_MAIN
     */
    public UI_MAIN() {
//        this.setLocationRelativeTo(null);
//        id = 1;
        initComponents();
        showTable();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        System.out.println("id: " + current_User.getUser().getId());
        System.out.println("username: " + current_User.getUser().getUsername());
        System.out.println("password: " + current_User.getUser().getPassword());
        setTxtnamelogin(current_User.getUser().getUsername());
//        CardLayout cardLayout = (CardLayout) pnlCenter.getLayout();
//        cardLayout.show(pnlCenter, "showTableCard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        panelRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        btnShowinfo = new javax.swing.JButton();
        btnAdduser = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        Order_Tour = new javax.swing.JButton();
        btnAddTour = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        ListTour = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnamelogin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        item_Tour1 = new View.Item_Tour();
        item_Tour2 = new View.Item_Tour();
        jPanel1 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        ShowTable = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InsertTable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_InputUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_InputPassword = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        AddTour = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtnametour = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        labelimg = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(255, 255, 255));
        pnlSide.setPreferredSize(new java.awt.Dimension(150, 0));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShowinfo.setBackground(new java.awt.Color(241, 202, 92));
        btnShowinfo.setFont(new java.awt.Font("Open Sans Medium", 1, 14)); // NOI18N
        btnShowinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showicon.png"))); // NOI18N
        btnShowinfo.setText("Show user");
        btnShowinfo.setBorder(null);
        btnShowinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowinfoMouseClicked(evt);
            }
        });
        pnlSide.add(btnShowinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 150, -1));

        btnAdduser.setBackground(new java.awt.Color(241, 202, 92));
        btnAdduser.setFont(new java.awt.Font("Open Sans Medium", 1, 14)); // NOI18N
        btnAdduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adduser.png"))); // NOI18N
        btnAdduser.setText("Thêm user");
        btnAdduser.setBorder(null);
        btnAdduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdduserMouseClicked(evt);
            }
        });
        pnlSide.add(btnAdduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 150, 40));

        btnLogout.setBackground(new java.awt.Color(241, 202, 92));
        btnLogout.setFont(new java.awt.Font("Open Sans Medium", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.setBorder(null);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        pnlSide.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 150, 40));

        Order_Tour.setBackground(new java.awt.Color(241, 202, 92));
        Order_Tour.setFont(new java.awt.Font("Open Sans Medium", 1, 14)); // NOI18N
        Order_Tour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking2.png"))); // NOI18N
        Order_Tour.setText("ĐẶT TOUR");
        Order_Tour.setBorder(null);
        Order_Tour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Order_TourMouseClicked(evt);
            }
        });
        pnlSide.add(Order_Tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, 40));

        btnAddTour.setBackground(new java.awt.Color(241, 202, 92));
        btnAddTour.setFont(new java.awt.Font("Open Sans Medium", 1, 14)); // NOI18N
        btnAddTour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addtour.png"))); // NOI18N
        btnAddTour.setText("Thêm Tour");
        btnAddTour.setBorder(null);
        btnAddTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTourMouseClicked(evt);
            }
        });
        pnlSide.add(btnAddTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 40));

        panelRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(225, 225, 225));
        pnlCenter.setLayout(new java.awt.CardLayout());

        ListTour.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(57, 55, 55));

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 202, 92));
        jLabel6.setText("User đang đăng nhập: ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N

        txtnamelogin.setFont(new java.awt.Font("Open Sans Medium", 1, 14)); // NOI18N
        txtnamelogin.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnamelogin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnamelogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListTour.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(460, 458));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 100, 50));
        jPanel2.add(item_Tour1);
        jPanel2.add(item_Tour2);

        ListTour.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ListTour.add(jPanel1, java.awt.BorderLayout.LINE_START);
        ListTour.add(jScrollBar1, java.awt.BorderLayout.EAST);

        pnlCenter.add(ListTour, "ListTour");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("Thông tin đăng nhập", jScrollPane1);

        javax.swing.GroupLayout ShowTableLayout = new javax.swing.GroupLayout(ShowTable);
        ShowTable.setLayout(ShowTableLayout);
        ShowTableLayout.setHorizontalGroup(
            ShowTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1429, Short.MAX_VALUE)
        );
        ShowTableLayout.setVerticalGroup(
            ShowTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
        );

        pnlCenter.add(ShowTable, "ShowTable");

        jLabel1.setText("Nhập username");

        jLabel2.setText("TẠO TÀI KHOẢN");

        jLabel3.setText("Nhập password");

        txt_InputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_InputPasswordActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InsertTableLayout = new javax.swing.GroupLayout(InsertTable);
        InsertTable.setLayout(InsertTableLayout);
        InsertTableLayout.setHorizontalGroup(
            InsertTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTableLayout.createSequentialGroup()
                .addGroup(InsertTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertTableLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2))
                    .addGroup(InsertTableLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(InsertTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InsertTableLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InsertTableLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_InputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdd))))
                .addContainerGap(1010, Short.MAX_VALUE))
        );
        InsertTableLayout.setVerticalGroup(
            InsertTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTableLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(80, 80, 80)
                .addGroup(InsertTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_InputUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(InsertTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_InputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(btnAdd)
                .addGap(88, 88, 88))
        );

        pnlCenter.add(InsertTable, "InsertTable");

        jLabel4.setText("Tên tour");

        jLabel5.setText("Giá");

        btnadd.setText("add");
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddMouseClicked(evt);
            }
        });

        labelimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBrowse.setText("Browse");
        btnBrowse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddTourLayout = new javax.swing.GroupLayout(AddTour);
        AddTour.setLayout(AddTourLayout);
        AddTourLayout.setHorizontalGroup(
            AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTourLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd)
                    .addGroup(AddTourLayout.createSequentialGroup()
                        .addGroup(AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnametour)
                            .addComponent(txtprice, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addGap(209, 209, 209)
                .addGroup(AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBrowse)
                    .addComponent(labelimg, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(570, Short.MAX_VALUE))
        );
        AddTourLayout.setVerticalGroup(
            AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTourLayout.createSequentialGroup()
                .addGroup(AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddTourLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnametour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(AddTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addComponent(btnadd))
                    .addGroup(AddTourLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(labelimg, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(btnBrowse)
                .addContainerGap(624, Short.MAX_VALUE))
        );

        pnlCenter.add(AddTour, "AddTour");

        panelRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTxtnamelogin(String txtnamelogin) {
        this.txtnamelogin.setText(txtnamelogin);
    }

    public JTextField getTxt_InputPassword() {
        return txt_InputPassword;
    }

    public void setTxt_InputPassword(JTextField txt_InputPassword) {
        this.txt_InputPassword = txt_InputPassword;
    }

    public JTextField getTxt_InputUsername() {
        return txt_InputUsername;
    }

    public void setTxt_InputUsername(JTextField txt_InputUsername) {
        this.txt_InputUsername = txt_InputUsername;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    private void btnShowinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowinfoMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) pnlCenter.getLayout();
        cardLayout.show(pnlCenter, "ShowTable");
        showTable();

    }//GEN-LAST:event_btnShowinfoMouseClicked

    private void btnAdduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdduserMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) pnlCenter.getLayout();
        cardLayout.show(pnlCenter, "InsertTable");
        showTable();
    }//GEN-LAST:event_btnAdduserMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        String username = txt_InputUsername.getText();
        String password = txt_InputPassword.getText();
        if(Connect_to_DB.register(username,password)){
            JOptionPane.showMessageDialog(jOptionPane1, "Thêm user thành công!");
//            insertTable(username,password);
        }
        else{
            JOptionPane.showMessageDialog(jOptionPane1, "Thêm user thất bại, hãy thử lại!");
        }

    }//GEN-LAST:event_btnAddMouseClicked

    private void txt_InputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_InputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_InputPasswordActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        UI_MAIN.this.dispose();
        new UI_Login().setVisible(true);

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void Order_TourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order_TourMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) pnlCenter.getLayout();
        cardLayout.show(pnlCenter, "ListTour");
        showTable();

    }//GEN-LAST:event_Order_TourMouseClicked

    private void btnAddTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTourMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) pnlCenter.getLayout();
        cardLayout.show(pnlCenter, "AddTour");
        showTable();
    }//GEN-LAST:event_btnAddTourMouseClicked

    private void btnaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseClicked
        // TODO add your handling code here:
        String nameTour = txtnametour.getText();
        String priceTour = txtprice.getText();
        Item_Tour newTour = new Item_Tour();
        newTour.setTxttnameTour(nameTour);
        newTour.setTxtPrice(priceTour);
        newTour.setRound_img1(getLabelIcon(labelimg));
        jPanel2.add(newTour);
    }//GEN-LAST:event_btnaddMouseClicked

    private Icon getLabelIcon(JLabel labelimage){
        return labelimage.getIcon();
    }

    private void btnBrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseMouseClicked
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("Image File", "jpg", "png", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image
            ImageIcon imageIcon = new ImageIcon(selectedImagePath);
            labelimg.setIcon(imageIcon);
        }

        
    }//GEN-LAST:event_btnBrowseMouseClicked

    /**
     * @param args the command line arguments
     */

//    private String column [] = {"Id","User","Password"};
//    DefaultTableModel model = new DefaultTableModel(null,column);
//
//    private void insertTable(String user, String password) {
//        jTable1.setModel(Controller_Table_User.getNewTable(user,password,model));
//    }

    private void showTable(){
        jTable1.setModel(Controller_Table_User.getTableUser());
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTour;
    private javax.swing.JPanel InsertTable;
    private javax.swing.JPanel ListTour;
    private javax.swing.JButton Order_Tour;
    private javax.swing.JPanel ShowTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddTour;
    private javax.swing.JButton btnAdduser;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnShowinfo;
    private javax.swing.JButton btnadd;
    private View.Item_Tour item_Tour1;
    private View.Item_Tour item_Tour2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelimg;
    private javax.swing.JPanel panelRoot;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JTextField txt_InputPassword;
    private javax.swing.JTextField txt_InputUsername;
    private javax.swing.JLabel txtnamelogin;
    private javax.swing.JTextField txtnametour;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
