/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Database.Connect_to_DB;

/**
 *
 * @author Admin
 */
public class UI_Register extends FormUI {

    /**
     * Creates new form UI_Register
     */
    public UI_Register() {
//        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        sign_up_button1 = new View.Sign_up_button();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 65, 187));
        jLabel1.setText("Create Account");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 20, 200, 33);

        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username);
        txt_username.setBounds(40, 125, 280, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 37, 37));
        jLabel2.setText("Create an account so you can access the database");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 60, 290, 16);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 103, 59, 16);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 167, 56, 15);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 236, 104, 15);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(73, 73, 73));
        jLabel6.setText("Already have an account");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(107, 373, 139, 14);

        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(40, 257, 280, 35);

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(40, 189, 280, 35);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture3.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 540, 355, 160);

        sign_up_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_up_button1MouseClicked(evt);
            }
        });
        jPanel1.add(sign_up_button1);
        sign_up_button1.setBounds(40, 310, 280, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(760, 0, 350, 680);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhminhhoalon_rs.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 780, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new UI_Login().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void bgimg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgimg1MouseClicked
        
    }//GEN-LAST:event_bgimg1MouseClicked

    private void sign_up_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_up_button1MouseClicked
        // TODO add your handling code here:
        String username = txt_username.getText();
        String password = new String(jPasswordField1.getPassword());
        String confirmPassword = new String(jPasswordField2.getPassword());
        if(checkValidRegister(username,password,confirmPassword)){
            if(Connect_to_DB.register(username,password)) {
                UI_Register.this.dispose();
                UI_Login loginForm = new UI_Login();
                loginForm.setVisible(true);

                jOptionPane1.showMessageDialog(loginForm, "Register Successful! ");
            }else{
                jOptionPane1.showMessageDialog(UI_Register.this, "Error: Username has alreadly existed! ");
            }
        }else{
            jOptionPane1.showMessageDialog(UI_Register.this, "Error: Username must at least 6 characters \n" +
                    "or password must match");
        }
    }//GEN-LAST:event_sign_up_button1MouseClicked
   //GEN-
    /**
     * @param args the command line arguments
     */

    private boolean checkValidRegister(String username, String password, String confirmPassword) {
            if(username.length() == 0 || password.length() == 0 || confirmPassword.length() == 0) return false;
            if(!password.equals(confirmPassword)) return false;
            if(username.length() < 6 ) return false;
            return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private View.Sign_up_button sign_up_button1;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
